export const CREATE_POST = 'POSTS/CREATE_POST';
export const REQUEST_POSTS = 'POSTS/REQUEST_POSTS';
export const FETCH_POSTS = 'POSTS/FETCH_POSTS';
export const SHOW_SPINNER = 'APP/SHOW_SPINNER';
export const HIDE_SPINNER = 'APP/HIDE_SPINNER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
